### ISSUE TITLE
Remove node_modules

### ISSUE THREAD

**Issue by HasanMdArik** [Rubayz/removebg-wrapper#2]
node_modules is not necessary rather bad to push with your code! Remove node_modules by adding it to the .gitignore file.. 
After that run,
 `git log`
Take(copy) the head of the upmost commit. Then run,
`git reset --soft $HEAD~ node_modules`
then,
`git restore --staged node_modules`. 
Then git add, commit the .gitignore file and push to GitHub...

**Comment by Rubayz** [comment]
Thanks for the suggestion.
